#!/usr/bin/env bash

apt-get update

# install Node.js and friends
apt-get install nodejs npm -y

# install and configure webserver
apt-get install nginx -y
cp /vagrant/nginx_fluffycupcakes /etc/nginx/sites-available/fluffycupcakes
chown root.root /etc/nginx/sites-available/fluffycupcakes
ln -s /etc/nginx/sites-available/fluffycupcakes /etc/nginx/sites-enabled/fluffycupcakes
service nginx restart

# start node - if used, this script will not end
# node /srv/web/app.js


echo ""
echo ""
echo ""
echo "Do a vagrant ssh"
echo "$ node /srv/web/app.js"
echo ""
echo "You should setup fluffycupcakes.local to point to 172.16.1.2 in /etc/hosts"
echo "Then you will be able to see the site in your browser on http://fluffycupcakes.local"
echo ""
echo "You will need to manually restart node if change any of the files"
echo ""