# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.5.3"

Vagrant.configure("2") do |config|

	config.vm.box = "hashicorp/precise64"
	config.vm.network "private_network", ip: "172.16.1.2"

	config.vm.hostname = "fluffycupcakes"

	config.vm.synced_folder "../web/", "/srv/web"

	config.vm.provision :shell, :path => "bootstrap"
end
